root: true

env:
    node: true
    es6: true
    mocha: true

extends:
    "airbnb"

rules:
  no-console: 0
#  Sometimes ya just gotta use them. Sorry @airbnb
  no-trailing-spaces: 1
  arrow-body-style: 0
  no-underscore-dangle:
    - 2
    - allowAfterThis: true

