root: true

env:
    node: true

extends:
    "airbnb"

rules:
  no-console: 0
#  Sometimes ya just gotta use them. Sorry @airbnb
  no-trailing-spaces: 1
  consistent-return: 1
  no-unused-vars: 1
  no-undef: 1
