language: node_js
node_js:
  - "6"
os:
  - linux
# Create the private configuration files
# The testing env doesn't need a firebase creds file
before_install:
  - echo -e '{"development":{"mail":{"username":"contractsgo@gmail.com","password":"$CI_MAIL_PASSWORD"}},"production":{"mail":{"username":"contractsgo@gmail.com","password":"$CI_MAIL_PASSWORD"}}}' >> ./config/private.config.json
install:
  - npm install
script:
  - npm run lint
  - npm test